//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persada.Fr.ModelView
{
    using System;
    using System.Collections.Generic;
    
    public class TOURIS_TV_USER_PROFILE
    {    
        public int ID { get; set; }
        public int USER_ID_ID { get; set; }
        public byte[] PHOTO { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> BORN { get; set; }
        public string ADDRESS { get; set; }
        public string DESCRIPTION { get; set; }
        public string JOB { get; set; }
        public string COMPANY { get; set; }
        public string HOBBY { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_TIME { get; set; }
        public string LAST_MODIFIED_BY { get; set; }
        public int ROW_STATUS { get; set; }
    }
}
