//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persada.Fr.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourismpediaEntities : DbContext
    {
        public TourismpediaEntities()
            : base("name=TourismpediaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TOURIS_TM_CATEGORY> TOURIS_TM_CATEGORY { get; set; }
        public virtual DbSet<TOURIS_TM_CITY> TOURIS_TM_CITY { get; set; }
        public virtual DbSet<TOURIS_TM_COUNTRY> TOURIS_TM_COUNTRY { get; set; }
        public virtual DbSet<TOURIS_TM_CULINARY> TOURIS_TM_CULINARY { get; set; }
        public virtual DbSet<TOURIS_TM_CULINARY_PHOTO> TOURIS_TM_CULINARY_PHOTO { get; set; }
        public virtual DbSet<TOURIS_TM_DISTRICTS> TOURIS_TM_DISTRICTS { get; set; }
        public virtual DbSet<TOURIS_TM_EVENT> TOURIS_TM_EVENT { get; set; }
        public virtual DbSet<TOURIS_TM_EVENT_PHOTO> TOURIS_TM_EVENT_PHOTO { get; set; }
        public virtual DbSet<TOURIS_TM_MENU> TOURIS_TM_MENU { get; set; }
        public virtual DbSet<TOURIS_TM_PARAMETER> TOURIS_TM_PARAMETER { get; set; }
        public virtual DbSet<TOURIS_TM_PROVINCE> TOURIS_TM_PROVINCE { get; set; }
        public virtual DbSet<TOURIS_TM_ROLE> TOURIS_TM_ROLE { get; set; }
        public virtual DbSet<TOURIS_TM_ROLE_MENU> TOURIS_TM_ROLE_MENU { get; set; }
        public virtual DbSet<TOURIS_TM_TESTIMONIAL> TOURIS_TM_TESTIMONIAL { get; set; }
        public virtual DbSet<TOURIS_TM_TOUR> TOURIS_TM_TOUR { get; set; }
        public virtual DbSet<TOURIS_TM_TOUR_PHOTO> TOURIS_TM_TOUR_PHOTO { get; set; }
        public virtual DbSet<TOURIS_TM_USER> TOURIS_TM_USER { get; set; }
        public virtual DbSet<TOURIS_TM_USER_DT> TOURIS_TM_USER_DT { get; set; }
        public virtual DbSet<TOURIS_TM_USER_PROFILE> TOURIS_TM_USER_PROFILE { get; set; }
        public virtual DbSet<TOURIS_TM_USER_PROFILE_SOSMED> TOURIS_TM_USER_PROFILE_SOSMED { get; set; }
        public virtual DbSet<TOURIS_TM_VILLAGE> TOURIS_TM_VILLAGE { get; set; }
    }
}
