//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persada.Fr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOURIS_TM_ROLE_MENU
    {
        public int ID { get; set; }
        public int ROLE_ID { get; set; }
        public int MENU_ID { get; set; }
        public int IS_ACCESS { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_TIME { get; set; }
        public string LAST_MODIFIED_BY { get; set; }
        public int ROW_STATUS { get; set; }
    
        public virtual TOURIS_TM_MENU TOURIS_TM_MENU { get; set; }
        public virtual TOURIS_TM_ROLE TOURIS_TM_ROLE { get; set; }
    }
}
