//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persada.Fr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOURIS_TM_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOURIS_TM_USER()
        {
            this.TOURIS_TM_USER_PROFILE = new HashSet<TOURIS_TM_USER_PROFILE>();
        }
    
        public int ID { get; set; }
        public string USER_ID { get; set; }
        public string USER_MAIL { get; set; }
        public string USER_NAME { get; set; }
        public int USER_DT_ID { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_TIME { get; set; }
        public string LAST_MODIFIED_BY { get; set; }
        public int ROW_STATUS { get; set; }
    
        public virtual TOURIS_TM_USER_DT TOURIS_TM_USER_DT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOURIS_TM_USER_PROFILE> TOURIS_TM_USER_PROFILE { get; set; }
    }
}
