//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persada.Fr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOURIS_TM_VILLAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOURIS_TM_VILLAGE()
        {
            this.TOURIS_TM_CULINARY = new HashSet<TOURIS_TM_CULINARY>();
            this.TOURIS_TM_EVENT = new HashSet<TOURIS_TM_EVENT>();
            this.TOURIS_TM_TOUR = new HashSet<TOURIS_TM_TOUR>();
        }
    
        public int ID { get; set; }
        public int DISTRICTS_ID { get; set; }
        public string CHILDHOOD_NAME { get; set; }
        public string CHILDHOOD_CODE { get; set; }
        public string CHILDHOOD_DESCRIPTION { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_TIME { get; set; }
        public string LAST_MODIFIED_BY { get; set; }
        public int ROW_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOURIS_TM_CULINARY> TOURIS_TM_CULINARY { get; set; }
        public virtual TOURIS_TM_DISTRICTS TOURIS_TM_DISTRICTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOURIS_TM_EVENT> TOURIS_TM_EVENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOURIS_TM_TOUR> TOURIS_TM_TOUR { get; set; }
    }
}
